### PR TITLE
Upgraded grid generation to use dice. Upgraded final output to includ…

### PR DESCRIPTION
**Pull request by bschaefer99**
…ed sorted list of words and their score.

### CODE REVIEW

**Comment by bschaefer99** [comment]
Cheers from St. Louis, MO @railto. I used your code to pre-generate some Boggle boards to play on a conference call with a dozen or so other folks. The solver made the scoring phase a breeze and we played 2 games in 15 minutes. 

Stay safe!

**Comment by mrailton** [comment]
Hey @bschaefer99, Thanks for the PR. To be honest I had completely forgotten about this. I created it as a basic example when I was in a coding bootcamp. I'm glad that it came in handy

I really like what you did, although could I possibly ask for 1 change. On the words output, could you put a 'header' to show what the number means (I know it's score, but makes it clearer).

Thanks again and I'm really glad it came in helpful

**Comment by mrailton** [comment]
Thanks again for your contribution.

**Comment by bschaefer99** [comment]
Good idea - committed!  

Yours was the first code I found when googling "Python Boggle Solver", and it seemed a shame to throw away the upgrades without sharing them. :D

**Pull request merged**
